import type { Component, DefineComponent } from 'vue';

type ThemeName = 'classic' | 'mono' | 'iron' | 'paper' | 'terminal' | 'warm';
type SurfaceVariant = 'outer' | 'inner' | 'clay';
type Size = 'sm' | 'md' | 'lg' | 'xl';
type ButtonVariant = 'default' | 'primary' | 'clay' | 'clayPrimary';
type FabVariant = 'default' | 'clay';
type KeyWidth = 'normal' | 'wide' | 'xwide' | 'space';
type BadgeTone = 'default' | 'primary' | 'success' | 'danger' | 'warning' | 'info';
type ToastTone = 'success' | 'danger' | 'warning' | 'info';
type UtilityTone = 'primary' | 'success' | 'danger' | 'warning' | 'info';
type IconVariant = 'raised' | 'sculpted';
type AIMessageRole = 'assistant' | 'user' | 'system';
type AIStatusState = 'idle' | 'streaming' | 'ready' | 'error';

type ElementType = string | Component;
type PolyProps<P = {}> = P & { as?: ElementType };
type PrimitiveComponent<P = {}> = DefineComponent<P>;

export declare const TactileTheme: PrimitiveComponent<PolyProps<{ theme?: ThemeName }>>;
export declare const TactileSurface: PrimitiveComponent<PolyProps<{ variant?: SurfaceVariant; size?: Size }>>;
export declare const TactileButton: PrimitiveComponent<{ active?: boolean; size?: Size; variant?: ButtonVariant }>;
export declare const TactileInput: PrimitiveComponent<{ clay?: boolean; modelValue?: string | number; type?: string }>;
export declare const TactileField: PrimitiveComponent<
  PolyProps<{ hint?: unknown; hintClass?: string; label?: unknown; labelClass?: string }>
>;
export declare const TactileFieldLabel: PrimitiveComponent<PolyProps>;
export declare const TactileFieldHint: PrimitiveComponent<PolyProps>;
export declare const TactileSelect: PrimitiveComponent<{ clay?: boolean; modelValue?: string | number }>;
export declare const TactileTextarea: PrimitiveComponent<{ clay?: boolean; modelValue?: string | number }>;
export declare const TactileCard: PrimitiveComponent<PolyProps<{ variant?: SurfaceVariant }>>;
export declare const TactileFab: PrimitiveComponent<{ size?: 'sm' | 'md' | 'lg'; variant?: FabVariant }>;
export declare const TactileSegment: PrimitiveComponent<{ active?: boolean }>;
export declare const TactileSegmented: PrimitiveComponent<{ clay?: boolean }>;
export declare const TactileTabs: PrimitiveComponent;
export declare const TactileTabList: PrimitiveComponent;
export declare const TactileTab: PrimitiveComponent<{ active?: boolean }>;
export declare const TactileTabPanel: PrimitiveComponent;
export declare const TactileSlider: PrimitiveComponent<{
  clay?: boolean;
  defaultValue?: number;
  disabled?: boolean;
  max?: number;
  min?: number;
  modelValue?: number;
  step?: number;
  thumbClass?: string;
  trackClass?: string;
}>;
export declare const TactileProgress: PrimitiveComponent<{ clay?: boolean; fillClass?: string; max?: number; value?: number }>;
export declare const TactileGauge: PrimitiveComponent<{ clay?: boolean; label?: unknown; max?: number; showValue?: boolean; value?: number }>;
export declare const TactileKeypad: PrimitiveComponent<{ clay?: boolean }>;
export declare const TactileKey: PrimitiveComponent<{ action?: boolean; clay?: boolean }>;
export declare const TactileKeyboard: PrimitiveComponent<{ clay?: boolean }>;
export declare const TactileKeyboardRow: PrimitiveComponent<{ clay?: boolean }>;
export declare const TactileKeyboardKey: PrimitiveComponent<{ clay?: boolean; primary?: boolean; width?: KeyWidth }>;
export declare const TactileBadge: PrimitiveComponent<PolyProps<{ clay?: boolean; tone?: BadgeTone }>>;
export declare const TactileAvatar: PrimitiveComponent<PolyProps<{ alt?: string; clay?: boolean; size?: Size; src?: string }>>;
export declare const TactileDivider: PrimitiveComponent<{ vertical?: boolean }>;
export declare const TactileCheckbox: PrimitiveComponent<{ clay?: boolean; modelValue?: boolean }>;
export declare const TactileSwitch: PrimitiveComponent<{ clay?: boolean; modelValue?: boolean }>;
export declare const TactileTone: PrimitiveComponent<PolyProps<{ tone?: UtilityTone }>>;
export declare const TactileModalOverlay: PrimitiveComponent<{ open?: boolean }>;
export declare const TactileModalHeader: PrimitiveComponent;
export declare const TactileModalTitle: PrimitiveComponent<PolyProps>;
export declare const TactileModalClose: PrimitiveComponent<{ type?: string }>;
export declare const TactileModalBody: PrimitiveComponent;
export declare const TactileModalFooter: PrimitiveComponent;
export declare const TactileModal: PrimitiveComponent<{
  closeLabel?: string;
  footer?: unknown;
  hideClose?: boolean;
  open?: boolean;
  overlayClass?: string;
  title?: unknown;
}>;
export declare const TactileToast: PrimitiveComponent<{
  hideClose?: boolean;
  icon?: unknown;
  message?: unknown;
  show?: boolean;
  title?: unknown;
  tone?: ToastTone;
}>;
export declare const TactileToastContainer: PrimitiveComponent;
export declare const TactileToastIcon: PrimitiveComponent;
export declare const TactileToastContent: PrimitiveComponent;
export declare const TactileToastTitle: PrimitiveComponent<PolyProps>;
export declare const TactileToastMessage: PrimitiveComponent<PolyProps>;
export declare const TactileToastClose: PrimitiveComponent<{ type?: string }>;
export declare const TactileAccordion: PrimitiveComponent;
export declare const TactileAccordionItem: PrimitiveComponent;
export declare const TactileAccordionTrigger: PrimitiveComponent;
export declare const TactileAccordionContent: PrimitiveComponent;
export declare const TactileAIChat: PrimitiveComponent<PolyProps>;
export declare const TactileAIMessage: PrimitiveComponent<PolyProps<{ role?: AIMessageRole }>>;
export declare const TactileAIMessageMeta: PrimitiveComponent<PolyProps>;
export declare const TactileAIMessageBody: PrimitiveComponent<PolyProps>;
export declare const TactileAIToolbar: PrimitiveComponent<PolyProps>;
export declare const TactileAIAction: PrimitiveComponent<{ type?: string }>;
export declare const TactileAISuggestions: PrimitiveComponent<PolyProps>;
export declare const TactileAISuggestion: PrimitiveComponent<{ type?: string }>;
export declare const TactileAIComposer: PrimitiveComponent<PolyProps>;
export declare const TactileAIComposerRow: PrimitiveComponent<PolyProps>;
export declare const TactileAIPrompt: PrimitiveComponent<{ modelValue?: string }>;
export declare const TactileAIStatus: PrimitiveComponent<PolyProps<{ state?: AIStatusState }>>;
export declare const TactileDisplay: PrimitiveComponent<
  PolyProps<{ label?: unknown; meta?: unknown; screenClass?: string; value?: unknown }>
>;
export declare const TactileDisplayLabel: PrimitiveComponent<PolyProps>;
export declare const TactileDisplayValue: PrimitiveComponent<PolyProps>;
export declare const TactileDisplayMeta: PrimitiveComponent<PolyProps>;
export declare const TactileKnob: PrimitiveComponent<{
  dialClass?: string;
  label?: unknown;
  max?: number;
  min?: number;
  showValue?: boolean;
  size?: number | string;
  value?: number;
}>;
export declare const TactileMeter: PrimitiveComponent<{
  fillClass?: string;
  label?: unknown;
  max?: number;
  showValue?: boolean;
  trackClass?: string;
  value?: number;
}>;
export declare const TactileDateInput: PrimitiveComponent<{ modelValue?: string; type?: string }>;
export declare const TactileTimeInput: PrimitiveComponent<{ modelValue?: string; type?: string }>;
export declare const TactileCalendar: PrimitiveComponent<PolyProps>;
export declare const TactileCalendarHeader: PrimitiveComponent<PolyProps>;
export declare const TactileCalendarTitle: PrimitiveComponent<PolyProps>;
export declare const TactileCalendarNav: PrimitiveComponent<{ type?: string }>;
export declare const TactileCalendarWeekdays: PrimitiveComponent<PolyProps>;
export declare const TactileCalendarWeekday: PrimitiveComponent<PolyProps>;
export declare const TactileCalendarGrid: PrimitiveComponent<PolyProps>;
export declare const TactileCalendarDay: PrimitiveComponent<{ muted?: boolean; selected?: boolean; today?: boolean; type?: string }>;
export declare const TactileTimeCard: PrimitiveComponent<PolyProps>;
export declare const TactileTimeLabel: PrimitiveComponent<PolyProps>;
export declare const TactileTimeValue: PrimitiveComponent<PolyProps>;
export declare const TactileClock: PrimitiveComponent<{ faceClass?: string; hour?: number; minute?: number; second?: number; size?: number | string }>;
export declare const TactileIcon: PrimitiveComponent<PolyProps<{ variant?: IconVariant }>>;
export declare const TactileText: PrimitiveComponent<PolyProps<{ sculpted?: boolean }>>;

declare const _default: {
  TactileTheme: typeof TactileTheme;
  TactileSurface: typeof TactileSurface;
  TactileButton: typeof TactileButton;
  TactileInput: typeof TactileInput;
  TactileField: typeof TactileField;
  TactileFieldLabel: typeof TactileFieldLabel;
  TactileFieldHint: typeof TactileFieldHint;
  TactileSelect: typeof TactileSelect;
  TactileTextarea: typeof TactileTextarea;
  TactileCard: typeof TactileCard;
  TactileFab: typeof TactileFab;
  TactileSegment: typeof TactileSegment;
  TactileSegmented: typeof TactileSegmented;
  TactileTabs: typeof TactileTabs;
  TactileTabList: typeof TactileTabList;
  TactileTab: typeof TactileTab;
  TactileTabPanel: typeof TactileTabPanel;
  TactileSlider: typeof TactileSlider;
  TactileProgress: typeof TactileProgress;
  TactileGauge: typeof TactileGauge;
  TactileKeypad: typeof TactileKeypad;
  TactileKey: typeof TactileKey;
  TactileKeyboard: typeof TactileKeyboard;
  TactileKeyboardRow: typeof TactileKeyboardRow;
  TactileKeyboardKey: typeof TactileKeyboardKey;
  TactileBadge: typeof TactileBadge;
  TactileAvatar: typeof TactileAvatar;
  TactileDivider: typeof TactileDivider;
  TactileCheckbox: typeof TactileCheckbox;
  TactileSwitch: typeof TactileSwitch;
  TactileTone: typeof TactileTone;
  TactileModalOverlay: typeof TactileModalOverlay;
  TactileModalHeader: typeof TactileModalHeader;
  TactileModalTitle: typeof TactileModalTitle;
  TactileModalClose: typeof TactileModalClose;
  TactileModalBody: typeof TactileModalBody;
  TactileModalFooter: typeof TactileModalFooter;
  TactileModal: typeof TactileModal;
  TactileToast: typeof TactileToast;
  TactileToastContainer: typeof TactileToastContainer;
  TactileToastIcon: typeof TactileToastIcon;
  TactileToastContent: typeof TactileToastContent;
  TactileToastTitle: typeof TactileToastTitle;
  TactileToastMessage: typeof TactileToastMessage;
  TactileToastClose: typeof TactileToastClose;
  TactileAccordion: typeof TactileAccordion;
  TactileAccordionItem: typeof TactileAccordionItem;
  TactileAccordionTrigger: typeof TactileAccordionTrigger;
  TactileAccordionContent: typeof TactileAccordionContent;
  TactileAIChat: typeof TactileAIChat;
  TactileAIMessage: typeof TactileAIMessage;
  TactileAIMessageMeta: typeof TactileAIMessageMeta;
  TactileAIMessageBody: typeof TactileAIMessageBody;
  TactileAIToolbar: typeof TactileAIToolbar;
  TactileAIAction: typeof TactileAIAction;
  TactileAISuggestions: typeof TactileAISuggestions;
  TactileAISuggestion: typeof TactileAISuggestion;
  TactileAIComposer: typeof TactileAIComposer;
  TactileAIComposerRow: typeof TactileAIComposerRow;
  TactileAIPrompt: typeof TactileAIPrompt;
  TactileAIStatus: typeof TactileAIStatus;
  TactileDisplay: typeof TactileDisplay;
  TactileDisplayLabel: typeof TactileDisplayLabel;
  TactileDisplayValue: typeof TactileDisplayValue;
  TactileDisplayMeta: typeof TactileDisplayMeta;
  TactileKnob: typeof TactileKnob;
  TactileMeter: typeof TactileMeter;
  TactileDateInput: typeof TactileDateInput;
  TactileTimeInput: typeof TactileTimeInput;
  TactileCalendar: typeof TactileCalendar;
  TactileCalendarHeader: typeof TactileCalendarHeader;
  TactileCalendarTitle: typeof TactileCalendarTitle;
  TactileCalendarNav: typeof TactileCalendarNav;
  TactileCalendarWeekdays: typeof TactileCalendarWeekdays;
  TactileCalendarWeekday: typeof TactileCalendarWeekday;
  TactileCalendarGrid: typeof TactileCalendarGrid;
  TactileCalendarDay: typeof TactileCalendarDay;
  TactileTimeCard: typeof TactileTimeCard;
  TactileTimeLabel: typeof TactileTimeLabel;
  TactileTimeValue: typeof TactileTimeValue;
  TactileClock: typeof TactileClock;
  TactileIcon: typeof TactileIcon;
  TactileText: typeof TactileText;
};

export default _default;
