import type { Component, DefineComponent } from 'vue';

type ThemeName = 'classic' | 'mono' | 'iron' | 'paper' | 'terminal' | 'warm';
type SurfaceVariant = 'outer' | 'inner' | 'clay';
type Size = 'sm' | 'md' | 'lg' | 'xl';
type ButtonVariant = 'default' | 'primary' | 'clay' | 'clayPrimary';
type FabVariant = 'default' | 'clay';
type KeyWidth = 'normal' | 'wide' | 'xwide' | 'space';
type BadgeTone = 'default' | 'primary' | 'success' | 'danger' | 'warning' | 'info';
type ToastTone = 'success' | 'danger' | 'warning' | 'info';
type UtilityTone = 'primary' | 'success' | 'danger' | 'warning' | 'info';
type IconVariant = 'raised' | 'sculpted';

type ElementType = string | Component;
type PolyProps<P = {}> = P & { as?: ElementType };
type PrimitiveComponent<P = {}> = DefineComponent<P>;

export declare const TactileTheme: PrimitiveComponent<PolyProps<{ theme?: ThemeName }>>;
export declare const TactileSurface: PrimitiveComponent<PolyProps<{ variant?: SurfaceVariant; size?: Size }>>;
export declare const TactileButton: PrimitiveComponent<{ active?: boolean; size?: Size; variant?: ButtonVariant }>;
export declare const TactileInput: PrimitiveComponent<{ clay?: boolean; modelValue?: string | number; type?: string }>;
export declare const TactileField: PrimitiveComponent<
  PolyProps<{ hint?: unknown; hintClass?: string; label?: unknown; labelClass?: string }>
>;
export declare const TactileFieldLabel: PrimitiveComponent<PolyProps>;
export declare const TactileFieldHint: PrimitiveComponent<PolyProps>;
export declare const TactileSelect: PrimitiveComponent<{ clay?: boolean; modelValue?: string | number }>;
export declare const TactileTextarea: PrimitiveComponent<{ clay?: boolean; modelValue?: string | number }>;
export declare const TactileCard: PrimitiveComponent<PolyProps<{ variant?: SurfaceVariant }>>;
export declare const TactileFab: PrimitiveComponent<{ size?: 'sm' | 'md' | 'lg'; variant?: FabVariant }>;
export declare const TactileSegment: PrimitiveComponent<{ active?: boolean }>;
export declare const TactileSegmented: PrimitiveComponent<{ clay?: boolean }>;
export declare const TactileTabs: PrimitiveComponent;
export declare const TactileTabList: PrimitiveComponent;
export declare const TactileTab: PrimitiveComponent<{ active?: boolean }>;
export declare const TactileTabPanel: PrimitiveComponent;
export declare const TactileSlider: PrimitiveComponent<{
  clay?: boolean;
  defaultValue?: number;
  disabled?: boolean;
  max?: number;
  min?: number;
  modelValue?: number;
  step?: number;
  thumbClass?: string;
  trackClass?: string;
}>;
export declare const TactileProgress: PrimitiveComponent<{ clay?: boolean; fillClass?: string; max?: number; value?: number }>;
export declare const TactileGauge: PrimitiveComponent<{ clay?: boolean; label?: unknown; max?: number; showValue?: boolean; value?: number }>;
export declare const TactileKeypad: PrimitiveComponent<{ clay?: boolean }>;
export declare const TactileKey: PrimitiveComponent<{ action?: boolean; clay?: boolean }>;
export declare const TactileKeyboard: PrimitiveComponent<{ clay?: boolean }>;
export declare const TactileKeyboardRow: PrimitiveComponent<{ clay?: boolean }>;
export declare const TactileKeyboardKey: PrimitiveComponent<{ clay?: boolean; primary?: boolean; width?: KeyWidth }>;
export declare const TactileBadge: PrimitiveComponent<PolyProps<{ clay?: boolean; tone?: BadgeTone }>>;
export declare const TactileAvatar: PrimitiveComponent<PolyProps<{ alt?: string; clay?: boolean; size?: Size; src?: string }>>;
export declare const TactileDivider: PrimitiveComponent<{ vertical?: boolean }>;
export declare const TactileCheckbox: PrimitiveComponent<{ clay?: boolean; modelValue?: boolean }>;
export declare const TactileSwitch: PrimitiveComponent<{ clay?: boolean; modelValue?: boolean }>;
export declare const TactileTone: PrimitiveComponent<PolyProps<{ tone?: UtilityTone }>>;
export declare const TactileModalOverlay: PrimitiveComponent<{ open?: boolean }>;
export declare const TactileModalHeader: PrimitiveComponent;
export declare const TactileModalTitle: PrimitiveComponent<PolyProps>;
export declare const TactileModalClose: PrimitiveComponent<{ type?: string }>;
export declare const TactileModalBody: PrimitiveComponent;
export declare const TactileModalFooter: PrimitiveComponent;
export declare const TactileModal: PrimitiveComponent<{
  closeLabel?: string;
  footer?: unknown;
  hideClose?: boolean;
  open?: boolean;
  overlayClass?: string;
  title?: unknown;
}>;
export declare const TactileToast: PrimitiveComponent<{
  hideClose?: boolean;
  icon?: unknown;
  message?: unknown;
  show?: boolean;
  title?: unknown;
  tone?: ToastTone;
}>;
export declare const TactileToastContainer: PrimitiveComponent;
export declare const TactileToastIcon: PrimitiveComponent;
export declare const TactileToastContent: PrimitiveComponent;
export declare const TactileToastTitle: PrimitiveComponent<PolyProps>;
export declare const TactileToastMessage: PrimitiveComponent<PolyProps>;
export declare const TactileToastClose: PrimitiveComponent<{ type?: string }>;
export declare const TactileAccordion: PrimitiveComponent;
export declare const TactileAccordionItem: PrimitiveComponent;
export declare const TactileAccordionTrigger: PrimitiveComponent;
export declare const TactileAccordionContent: PrimitiveComponent;
export declare const TactileIcon: PrimitiveComponent<PolyProps<{ variant?: IconVariant }>>;
export declare const TactileText: PrimitiveComponent<PolyProps<{ sculpted?: boolean }>>;

declare const _default: {
  TactileTheme: typeof TactileTheme;
  TactileSurface: typeof TactileSurface;
  TactileButton: typeof TactileButton;
  TactileInput: typeof TactileInput;
  TactileField: typeof TactileField;
  TactileFieldLabel: typeof TactileFieldLabel;
  TactileFieldHint: typeof TactileFieldHint;
  TactileSelect: typeof TactileSelect;
  TactileTextarea: typeof TactileTextarea;
  TactileCard: typeof TactileCard;
  TactileFab: typeof TactileFab;
  TactileSegment: typeof TactileSegment;
  TactileSegmented: typeof TactileSegmented;
  TactileTabs: typeof TactileTabs;
  TactileTabList: typeof TactileTabList;
  TactileTab: typeof TactileTab;
  TactileTabPanel: typeof TactileTabPanel;
  TactileSlider: typeof TactileSlider;
  TactileProgress: typeof TactileProgress;
  TactileGauge: typeof TactileGauge;
  TactileKeypad: typeof TactileKeypad;
  TactileKey: typeof TactileKey;
  TactileKeyboard: typeof TactileKeyboard;
  TactileKeyboardRow: typeof TactileKeyboardRow;
  TactileKeyboardKey: typeof TactileKeyboardKey;
  TactileBadge: typeof TactileBadge;
  TactileAvatar: typeof TactileAvatar;
  TactileDivider: typeof TactileDivider;
  TactileCheckbox: typeof TactileCheckbox;
  TactileSwitch: typeof TactileSwitch;
  TactileTone: typeof TactileTone;
  TactileModalOverlay: typeof TactileModalOverlay;
  TactileModalHeader: typeof TactileModalHeader;
  TactileModalTitle: typeof TactileModalTitle;
  TactileModalClose: typeof TactileModalClose;
  TactileModalBody: typeof TactileModalBody;
  TactileModalFooter: typeof TactileModalFooter;
  TactileModal: typeof TactileModal;
  TactileToast: typeof TactileToast;
  TactileToastContainer: typeof TactileToastContainer;
  TactileToastIcon: typeof TactileToastIcon;
  TactileToastContent: typeof TactileToastContent;
  TactileToastTitle: typeof TactileToastTitle;
  TactileToastMessage: typeof TactileToastMessage;
  TactileToastClose: typeof TactileToastClose;
  TactileAccordion: typeof TactileAccordion;
  TactileAccordionItem: typeof TactileAccordionItem;
  TactileAccordionTrigger: typeof TactileAccordionTrigger;
  TactileAccordionContent: typeof TactileAccordionContent;
  TactileIcon: typeof TactileIcon;
  TactileText: typeof TactileText;
};

export default _default;
